=== tg73/RatOS-configurator/configuration/filament-sensors/filament-sensor-definition-schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://os.ratrig.com/filament-sensor-definition.schema.json",
	"title": "Filament Sensor Definition",
	"description": "A RatOS-supported filament sensor",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"$schema": {
			"description": "The schema used for this file",
			"type": "string"
		},
		"type": {
			"description": "The type of this configuration file",
			"type": "string",
			"const": "filament-sensor"
		},
		"name": {
			"description": "The name of the filament sensor",
			"type": "string"
		},
		"description": {
			"description": "A description of the filament sensor",
			"type": "string"
		},
		"manufacturer": {
			"description": "The name of the manufacturer of this filament sensor",
			"type": "string"
		},
		"hasButton": {
			"description": "Whether this filament sensor has a button",
			"type": "boolean",
			"default": false
		},
		"sensePinAlias": {
			"description": "The pin alias for the filament sensor sense pin. Default is 'filament_sensor_sense_pin'.",
			"type": "string",
			"default": "filament_sensor_sense_pin"
		},
		"buttonPinAlias": {
			"description": "The pin alias for the filament sensor button pin. Default is 'filament_sensor_button_pin'.",
			"type": "string",
			"default": "filament_sensor_button_pin"
		},
		"additionalRequiredPins": {
			"description": "Additional pin aliases required by this filament sensor. Note that filament_sensor_sense_pin is always required, and filament_sensor_button_pin is required if hasButton is true.",
			"type": "array",
			"items": {
				"type": "string"
			},
			"uniqueItems": true
		},
		"template": {
			"description": "TypeScript template for this filament sensor (path relative to /src/templates/filament-sensors/)",
			"type": "string"
		},
		"templateProperties": {
			"description": "Custom properties for this filament sensor. These properties can be consumed by the template, enabling template reuse for similar filament sensors.",
			"type": "object",
			"additionalProperties": true
		}
	},
	"required": [
		"type",
		"name",
		"description",
		"manufacturer",
		"template"
	]	
}

=== tg73/RatOS-configurator/configuration/filament-sensors/generic-inverted/filament-sensor-definition.json
{
	"$schema": "../filament-sensor-definition-schema.json",
	"type": "filament-sensor",
	"name": "Generic Filament Sensor (inverted)",
	"description": "Generic filament sensor with inverted sense pin",
	"manufacturer": "Generic",
	"template": "generic.ts",
	"templateProperties": {
		"invertSensePin": true
	}
}
